name: CI

on:
  push:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          cd services/api
          pip install fastapi "uvicorn[standard]" pydantic pytest coverage hypothesis sqlalchemy psycopg2-binary
      - name: Pytest
        run: |
          cd services/api
          pytest